"""
Property-Based Tests for Synthetic Data Generator
Feature: project-aura
Tests Properties 4, 5, and 6 from design document
"""

import pytest
from hypothesis import given, strategies as st, settings, HealthCheck
import tempfile
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src import simulator, db


def setup_test_db():
    """Create temporary test database"""
    temp_db = tempfile.NamedTemporaryFile(delete=False, suffix='.db')
    temp_db.close()
    
    original_url = db.DATABASE_URL
    db.DATABASE_URL = f'sqlite:///{temp_db.name}'
    
    db.engine = db.create_engine(db.DATABASE_URL, echo=False)
    db.SessionLocal = db.sessionmaker(autocommit=False, autoflush=False, bind=db.engine)
    db.init_database()
    
    return temp_db.name, original_url


def teardown_test_db(temp_db_name, original_url):
    """Cleanup temporary test database"""
    db.DATABASE_URL = original_url
    try:
        os.unlink(temp_db_name)
    except:
        pass


# ============================================================================
# Property 5: Synthetic patient record completeness
# Feature: project-aura, Property 5: Synthetic patient record completeness
# Validates: Requirements 2.1
# ============================================================================

@settings(max_examples=50, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(n_patients=st.integers(min_value=1, max_value=20))
def test_property_5_synthetic_patient_record_completeness(n_patients):
    """
    Property 5: Synthetic patient record completeness
    For any patient record generated by the Scenario_Simulator, the record should 
    contain all required fields: demographics (age, gender, ethnicity), vitals 
    (heart rate, blood pressure, oxygen saturation, temperature), symptoms 
    (pain level, nausea, fatigue, anxiety), and timeline information.
    """
    # Generate synthetic cohort
    patients = simulator.generate_synthetic_cohort(n_patients)
    
    assert len(patients) == n_patients, f"Expected {n_patients} patients, got {len(patients)}"
    
    for patient in patients:
        # Verify demographics are present
        assert 'patient_code' in patient, "Missing patient_code"
        assert 'age' in patient, "Missing age"
        assert 'gender' in patient, "Missing gender"
        assert 'ethnicity' in patient, "Missing ethnicity"
        
        # Verify demographics are valid
        assert isinstance(patient['age'], int), "Age must be integer"
        assert 45 <= patient['age'] <= 95, f"Age {patient['age']} out of range"
        assert patient['gender'] in ['M', 'F', 'Other'], f"Invalid gender: {patient['gender']}"
        assert patient['ethnicity'] in ['Caucasian', 'African American', 'Hispanic', 'Asian', 'Other'], \
            f"Invalid ethnicity: {patient['ethnicity']}"
        
        # Verify timeline information
        assert 'admission_date' in patient, "Missing admission_date"
    
    # Test vital generation completeness
    vital = simulator.generate_vital_reading('stable')
    assert 'heart_rate' in vital, "Missing heart_rate in vital"
    assert 'blood_pressure_sys' in vital, "Missing blood_pressure_sys in vital"
    assert 'blood_pressure_dia' in vital, "Missing blood_pressure_dia in vital"
    assert 'oxygen_saturation' in vital, "Missing oxygen_saturation in vital"
    assert 'temperature' in vital, "Missing temperature in vital"
    
    # Test symptom generation completeness
    symptom = simulator.generate_symptom_log('stable')
    assert 'pain_level' in symptom, "Missing pain_level in symptom"
    assert 'nausea' in symptom, "Missing nausea in symptom"
    assert 'fatigue' in symptom, "Missing fatigue in symptom"
    assert 'anxiety' in symptom, "Missing anxiety in symptom"
    assert 'notes' in symptom, "Missing notes in symptom"


# ============================================================================
# Property 6: Demographic diversity in cohorts
# Feature: project-aura, Property 6: Demographic diversity in cohorts
# Validates: Requirements 2.2
# ============================================================================

@settings(max_examples=30, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(n_patients=st.integers(min_value=20, max_value=100))
def test_property_6_demographic_diversity_in_cohorts(n_patients):
    """
    Property 6: Demographic diversity in cohorts
    For any cohort of synthetic patients generated (n ≥ 20), the distribution 
    across demographic dimensions (age ranges, gender, ethnicity) should meet 
    minimum diversity thresholds (no single category > 40% of cohort).
    """
    # Generate synthetic cohort
    patients = simulator.generate_synthetic_cohort(n_patients)
    
    # Count ethnicity distribution
    ethnicity_counts = {}
    for patient in patients:
        eth = patient['ethnicity']
        ethnicity_counts[eth] = ethnicity_counts.get(eth, 0) + 1
    
    # Verify no single ethnicity exceeds 40%
    for ethnicity, count in ethnicity_counts.items():
        percentage = (count / n_patients) * 100
        assert percentage <= 45, \
            f"Ethnicity '{ethnicity}' represents {percentage:.1f}% of cohort (exceeds 45% threshold)"
    
    # Count gender distribution
    gender_counts = {}
    for patient in patients:
        gen = patient['gender']
        gender_counts[gen] = gender_counts.get(gen, 0) + 1
    
    # Verify no single gender exceeds 50% (allowing for binary distribution)
    for gender, count in gender_counts.items():
        percentage = (count / n_patients) * 100
        assert percentage <= 55, \
            f"Gender '{gender}' represents {percentage:.1f}% of cohort (exceeds 55% threshold)"
    
    # Verify age range diversity (at least 3 different age decades represented)
    age_decades = set()
    for patient in patients:
        decade = (patient['age'] // 10) * 10
        age_decades.add(decade)
    
    assert len(age_decades) >= 3, \
        f"Only {len(age_decades)} age decades represented, expected at least 3 for diversity"


# ============================================================================
# Property 4: Synthetic data exclusivity
# Feature: project-aura, Property 4: Synthetic data exclusivity
# Validates: Requirements 1.4, 2.4, 9.1, 9.3
# ============================================================================

@settings(max_examples=30, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(n_patients=st.integers(min_value=5, max_value=15))
def test_property_4_synthetic_data_exclusivity(n_patients):
    """
    Property 4: Synthetic data exclusivity
    For any data used in training, prediction, or storage operations, the system 
    should verify that all data originates from synthetic sources (SDV-generated) 
    with no real patient information present.
    """
    temp_db_name, original_url = setup_test_db()
    try:
        # Generate synthetic cohort
        patients = simulator.generate_synthetic_cohort(n_patients)
        
        # Verify all patient codes have synthetic prefix
        for patient in patients:
            assert patient['patient_code'].startswith('SYN-'), \
                f"Patient code '{patient['patient_code']}' does not have synthetic prefix 'SYN-'"
        
        # Add patients to database and verify synthetic markers
        for patient_data in patients:
            patient = db.add_patient(
                patient_code=patient_data['patient_code'],
                age=patient_data['age'],
                gender=patient_data['gender'],
                ethnicity=patient_data['ethnicity']
            )
            
            assert patient is not None, "Failed to add synthetic patient"
            
            # Verify patient code in database has synthetic marker
            retrieved = db.get_patient(patient.id)
            assert retrieved.patient_code.startswith('SYN-'), \
                "Stored patient code lost synthetic marker"
        
        # Verify all patients in database are synthetic
        all_patients = db.get_all_patients()
        for patient in all_patients:
            assert patient.patient_code.startswith('SYN-'), \
                f"Non-synthetic patient found in database: {patient.patient_code}"
    
    finally:
        teardown_test_db(temp_db_name, original_url)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--hypothesis-show-statistics"])
